server:
  port: 8080
  tomcat:
    max-threads: 400
    max-connections: 10000
    accept-count: 1000
    connection-timeout: 5000

grpc:
  client:
    account-service:
      address: localhost
      port: 9090
      negotiationType: plaintext
  server:
    port: 9091

spring:
  application:
    name: api-gateway

app:
  worker-pool:
    size: 32