server:
  port: 8080
  tomcat:
    max-threads: 400
    max-connections: 10000
    accept-count: 1000
    connection-timeout: 5000
  server:
    servlet:
      session:
        timeout: 30m
  error:
    include-message: always

grpc:
  client:
    account-service:
      address: localhost
      port: 9090
      negotiationType: plaintext
  server:
    port: 9091

spring:
  application:
    name: api-gateway
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

pusher:
  app-key: 6ba8c285cf1ace0586de
  app-secret: 1095c25bd55175aa9f05
  app-id: 1848195
  cluster: ap3

kafka:
  topic:
    welcome-email: send-welcome-email

logging:
  level:
    org.springframework.security: DEBUG
    com.meenachinmay.api_gateway: DEBUG
jwt:
  secret: your_jwt_secret_key_here
  expiration: 86400000 # 24 hours in milliseconds

app:
  worker-pool:
    size: 32
